Repository neo4j/docs-status-codes, pull requests merged in 2023-02, with the labels that each got.

#37 Update the caption of the notification details tables
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry-pick this to 5.x, dev

#38 update the caption of the notification details tables
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, 5.x

#32 Add deprecation warning for using differently ordered return items in UNIONs
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: dev, 5.5

#40 Add example for new notification "Binding a variable-length relationship variable more than once"
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.6

#41 Update Neo4j version
  antora.yml
Labels: 5.6

#42 Update packages
  package-lock.json
  package.json
  preview.yml
  publish.yml
Labels: dev

#39 Deprecate id() function
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: dev, 5.6
