Repository neo4j/docs-status-codes, pull requests merged in 2023-01, with the labels that each got.

#22 Update index.adoc
  modules/ROOT/pages/index.adoc
Labels: 4.4

#31 Add some info about error codes
  modules/ROOT/pages/errors/index.adoc
Labels: cherry-pick this to 5.x, dev

#34 Update neo4j version
  antora.yml
Labels: 5.5
