Repository neo4j/docs-status-codes, pull requests merged in 2023-05, with the labels that each got.

#56 Update notification detail for deprecated function and procedures.
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.8

#58 Add NODES 23 ad
  publish.yml
Labels: 5.x

#55 Аdd the guidelines for writing notifications to the readme
  README.adoc
Labels: 5.x

#59 Аdd the guidelines for writing notifications to the readme (#55)
  README.adoc
Labels: cherry picked, 5.x

#61 Update the guidelines for writing codes
  README.adoc
Labels: cherry-pick this to 5.x

#60 Remove Neo.ClientNotification from the right navigation
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry-pick this to 5.x, 5.x

#64 Add example for new notification "Binding a variable-length relations…
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, 5.x
