Repository neo4j/docs-status-codes, pull requests merged in 2023-11, with the labels that each got.

#90 Add a section about severity level to the guidelines
  README.adoc
Labels: cherry-pick this to 5.x

#93 Add a section about severity level to the guidelines (#90)
  README.adoc
Labels: cherry picked, 5.x

#86 Add `CordonedServersExistedDuringAllocation` notification
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.15

#95 bump version
  antora.yml
Labels: 4.4, do not cherry-pick

#92 add identifier unicode deprecation example
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: dev

#96 Cherry-picks all 5.14 features
  antora.yml
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, 5.x

#97 Update the preview version to 5.15
  antora.yml
Labels: dev

#98 Add connections ad
  publish.yml
Labels: 5.x
