Repository neo4j/docs-status-codes, pull requests merged in 2023-10, with the labels that each got.

#72 Adding Topology notification category and ServerAlreadyEnabled
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/pages/notifications/index.adoc
Labels: dev, 5.13

#76 Improve exhaustive shortest path section (#74)
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, 5.x

#77 Add missing error codes and their descriptions
  modules/ROOT/pages/errors/all-errors.adoc
Labels: cherry-pick this to 5.x, dev

#78 Add missing error codes and their descriptions (#77)
  modules/ROOT/pages/errors/all-errors.adoc
Labels: cherry picked, 5.x

#73 Update readme to include guidelines for writing/updating errors
  README.adoc
Labels: 5.x

#81 Update readme to include guidelines for writing/updating errors
  README.adoc
Labels: cherry picked, 5.x

#82 4.4 update exact version
  antora.yml
  preview.yml
  publish.yml
Labels: 4.4, do not cherry-pick

#83 update class and subclass
  README.adoc
  modules/ROOT/pages/errors/all-errors.adoc
  modules/ROOT/pages/errors/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/pages/notifications/index.adoc
Labels: cherry-pick this to 5.x

#87 update class and subclass (#83)
  README.adoc
  modules/ROOT/pages/errors/all-errors.adoc
  modules/ROOT/pages/errors/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/notifications/index.adoc
Labels: cherry picked, 5.x

#88 Cherry-pick 5.13 PRs
  antora.yml
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/pages/notifications/index.adoc
Labels: cherry picked, 5.x

#89 update the version to 5.14
  antora.yml
Labels: 5.14

#85 Side effect implication notification
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry-pick this to 5.x
