Repository neo4j/docs-status-codes, pull requests merged in 2023-12, with the labels that each got.

#99 Add `CordonedServersExistedDuringAllocation` notification (#86)
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, 5.15

#102 remove connections ad
  publish.yml
Labels: 5.x, do not cherry-pick

#108 update version to 4.4.29
  antora.yml
Labels: 4.4
