Repository neo4j/docs-status-codes, pull requests merged in 2024-02, with the labels that each got.

#119 Add `IndexOrConstraintAlreadyExists` and `IndexOrConstraintDoesNotExist` notifications and new `SCHEMA` notification category
  README.adoc
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/pages/notifications/index.adoc
Labels: 5.17

#122 Add an example of a parameter within backticks
  README.adoc
Labels: cherry-pick this to 5.x

#123 Add an example of a parameter within backticks (#122)
  README.adoc
Labels: cherry picked, 5.x

#121 Updating link to cypher manual
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: bug, cherry-pick this to 5.x

#124 Updating link to cypher manual (#121)
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, 5.x

#125 Document CDC related error codes
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/errors/all-errors.adoc
Labels: cherry-pick this to 5.x

#127 Update config settings according to name changes in 5.x series
  modules/ROOT/pages/errors/all-errors.adoc
Labels: cherry-pick this to 5.x
