Repository neo4j/docs-status-codes, pull requests merged in 2024-09, with the labels that each got.

#178 Update the exact version to 4.4.37
  antora.yml
Labels: 4.4

#175 Added superfluous optional notification
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.24

#142 Add notifications for linked users
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.24

#181 Update the v.number to 5.25
  antora.yml
Labels: 5.25
