Repository neo4j/docs-status-codes, pull requests merged in 2024-12, with the labels that each got.

#230 Apply feedback from review
  modules/ROOT/pages/errors/all-errors.adoc
  modules/ROOT/pages/errors/gql-errors.adoc
  modules/ROOT/pages/errors/index.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.26

#232 Add status code 42NA8 and 42NA9
  modules/ROOT/pages/errors/gql-errors.adoc
Labels: 2025.01

#231 Add notifications for WAIT commands
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/pages/notifications/index.adoc
Labels: 2025.01, Cypher 25

#235 Update the changelog for 5.x
  modules/ROOT/pages/changelogs.adoc
Labels: cherry-pick this to 5.x

#234 Update the `dev` branch for 2025.01 release
  antora.yml
  package.json
  publish.yml
Labels: 2025.01

#236 Add LTS label to 5.26
  antora.yml
Labels: 5.x, do not cherry-pick

#238 Update the version to 4.4.40
  antora.yml
Labels: 4.4

#239 Swap some examples tabs and fix some bugs
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 2025.01

#240 Add status codes from neo4j PR 28647
  modules/ROOT/pages/errors/gql-errors.adoc
Labels: dev, gqlstatus-errors

#246 Add status codes from neo4j PR 28821
  modules/ROOT/pages/errors/gql-errors.adoc
Labels: dev, gqlstatus-errors
