Repository neo4j/docs-status-codes, pull requests merged in 2025-08, with the labels that each got.

#368 Error 51N77 missing from content nav causing broken link
  modules/ROOT/content-nav.adoc
Labels: cherry-pick this to main

#371 Introduce 22NBD - Unsupported Struct
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22NBD.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: cherry-pick this to main

#373 Introduce 22NBD - Unsupported Struct (#371)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22NBD.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: cherry picked, main

#376 Update the exact version to 5.26.11
  antora.yml
Labels: 5.x, this branch only

#377 Update to 4.4.45
  antora.yml
Labels: 4.4, this branch only
