Repository neo4j/docs-status-codes, pull requests merged in 2025-04, with the labels that each got.

#272 Add 42N3A-42N3B-42N3C and update 42N39
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42N3A.adoc
  modules/ROOT/pages/errors/gql-errors/42N3B.adoc
  modules/ROOT/pages/errors/gql-errors/42N3C.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: DO NOT MERGE, Cypher 25

#294 Error missing in the content-nav
  modules/ROOT/content-nav.adoc
Labels: cherry-pick-this-to-cypher25

#295 Error missing in the content-nav (#294)
  modules/ROOT/content-nav.adoc
Labels: cherry picked

#298 Fix a wrong title for 52N28 (#296)
  modules/ROOT/pages/errors/gql-errors/52N28.adoc
Labels: cherry picked

#293 Typo causing broken link #280
  modules/ROOT/content-nav.adoc
Labels: cherry picked

#299 Add errors implemented in 2025.04
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22N83.adoc
  modules/ROOT/pages/errors/gql-errors/22NA3.adoc
  modules/ROOT/pages/errors/gql-errors/22NB7.adoc
  modules/ROOT/pages/errors/gql-errors/22NB8.adoc
  modules/ROOT/pages/errors/gql-errors/42I30.adoc
  modules/ROOT/pages/errors/gql-errors/42N0B.adoc
  modules/ROOT/pages/errors/gql-errors/42N25.adoc
  modules/ROOT/pages/errors/gql-errors/42N41.adoc
  modules/ROOT/pages/errors/gql-errors/42N52.adoc
  modules/ROOT/pages/errors/gql-errors/42N87.adoc
  modules/ROOT/pages/errors/gql-errors/42N92.adoc
  modules/ROOT/pages/errors/gql-errors/42N94.adoc
  modules/ROOT/pages/errors/gql-errors/42N95.adoc
  modules/ROOT/pages/errors/gql-errors/42N96.adoc
  modules/ROOT/pages/errors/gql-errors/42NA0.adoc
  modules/ROOT/pages/errors/gql-errors/42NA1.adoc
  modules/ROOT/pages/errors/gql-errors/42NA2.adoc
  modules/ROOT/pages/errors/gql-errors/42NA3.adoc
  modules/ROOT/pages/errors/gql-errors/42NA4.adoc
  modules/ROOT/pages/errors/gql-errors/51N31.adoc
  modules/ROOT/pages/errors/gql-errors/51N58.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.04

#305 Main merge dev
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/08N19.adoc
  modules/ROOT/pages/errors/gql-errors/08N20.adoc
  modules/ROOT/pages/errors/gql-errors/08N21.adoc
  modules/ROOT/pages/errors/gql-errors/22004.adoc
  modules/ROOT/pages/errors/gql-errors/22012.adoc
  modules/ROOT/pages/errors/gql-errors/22N83.adoc
  modules/ROOT/pages/errors/gql-errors/22NA3.adoc
  modules/ROOT/pages/errors/gql-errors/22NB7.adoc
  modules/ROOT/pages/errors/gql-errors/22NB8.adoc
  modules/ROOT/pages/errors/gql-errors/2DN01.adoc
  modules/ROOT/pages/errors/gql-errors/42I30.adoc
  modules/ROOT/pages/errors/gql-errors/42I53.adoc
  modules/ROOT/pages/errors/gql-errors/42N0A.adoc
  modules/ROOT/pages/errors/gql-errors/42N0B.adoc
  modules/ROOT/pages/errors/gql-errors/42N25.adoc
  modules/ROOT/pages/errors/gql-errors/42N3A.adoc
  modules/ROOT/pages/errors/gql-errors/42N3B.adoc
  modules/ROOT/pages/errors/gql-errors/42N3C.adoc
  modules/ROOT/pages/errors/gql-errors/42N41.adoc
  modules/ROOT/pages/errors/gql-errors/42N52.adoc
  modules/ROOT/pages/errors/gql-errors/42N87.adoc
  modules/ROOT/pages/errors/gql-errors/42N92.adoc
  modules/ROOT/pages/errors/gql-errors/42N94.adoc
  modules/ROOT/pages/errors/gql-errors/42N95.adoc
  modules/ROOT/pages/errors/gql-errors/42N96.adoc
  modules/ROOT/pages/errors/gql-errors/42NA0.adoc
  modules/ROOT/pages/errors/gql-errors/42NA1.adoc
  modules/ROOT/pages/errors/gql-errors/42NA2.adoc
  modules/ROOT/pages/errors/gql-errors/42NA3.adoc
  modules/ROOT/pages/errors/gql-errors/42NA4.adoc
  modules/ROOT/pages/errors/gql-errors/50N18.adoc
  modules/ROOT/pages/errors/gql-errors/50N19.adoc
  modules/ROOT/pages/errors/gql-errors/50N20.adoc
  modules/ROOT/pages/errors/gql-errors/51N31.adoc
  modules/ROOT/pages/errors/gql-errors/51N58.adoc
  modules/ROOT/pages/errors/gql-errors/52N21.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: main
