Repository neo4j/docs-status-codes, pull requests merged in 2025-03, with the labels that each got.

#277 Update the v.number to 5.26.4
  antora.yml
Labels: 5.x, do not cherry-pick

#278 Remove 42002
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42002.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.03

#280 Typo causing broken link
  modules/ROOT/content-nav.adoc
Labels: cherry-pick this to main

#276 Add 50N23 for failed Call In Transactions retry
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/50N23.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.03

#283 Bump version to 4.4.42
  antora.yml
Labels: 4.4, this branch only

#275 Add examples to the glossary descriptions
  modules/ROOT/pages/errors/gql-errors/50N21.adoc
  modules/ROOT/pages/errors/gql-errors/52N36.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/partials/glossary.adoc
Labels: cherry-pick this to main

#285 Add examples to the glossary descriptions (#275)
  modules/ROOT/pages/errors/gql-errors/50N21.adoc
  modules/ROOT/pages/errors/gql-errors/52N36.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/partials/glossary.adoc
Labels: cherry picked

#290 Update the version to 2025.04
  antora.yml
Labels: 2025.04

#279 New Error - Vector coordinate type
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42I53.adoc
Labels: dev, 2025.04

#286 id() changed to a feature deprecated with replacement and move unsupported.dbms.shutdown example to features deprecated without a replacement
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 2025.04

#287 Change parameter serverName to server
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: dev, gqlstatus-notifications, 2025.04

#288 Update message of 2DN01
  modules/ROOT/pages/errors/gql-errors/2DN01.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.04
