Repository neo4j/docs-status-codes, pull requests merged in 2025-09, with the labels that each got.

#378 Publish 2025.08
  antora.yml
Labels: main, this branch only

#379 Bump to 2025.09
  antora.yml
Labels: 2025.09

#372 Update workflows to v2
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-generate-html.yml
  .github/workflows/docs-pr-checks.yml
  .github/workflows/docs-teardown.yml
  package.json
  preview.yml
  publish.yml
Labels: cherry-pick this to main

#383 Update workflows to v2 (#372)
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-generate-html.yml
  .github/workflows/docs-pr-checks.yml
  .github/workflows/docs-teardown.yml
  package.json
  preview.yml
  publish.yml
Labels: cherry picked

#375 Error codes: 42I65 and 42I66
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42I65.adoc
  modules/ROOT/pages/errors/gql-errors/42I66.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.09

#381 Added error code 42I67 unsupported language feature
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42I67.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.09

#370 Update deprecation message for legacy text index providers.
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 2025.09

#374 Add 22NBE and 22NBF
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22NBE.adoc
  modules/ROOT/pages/errors/gql-errors/22NBF.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: 2025.09
