Repository neo4j/docs-status-codes, pull requests merged in 2025-07, with the labels that each got.

#352 Cypher 25 merge dev
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/all-errors.adoc
  modules/ROOT/pages/errors/gql-errors/08N19.adoc
  modules/ROOT/pages/errors/gql-errors/08N20.adoc
  modules/ROOT/pages/errors/gql-errors/08N21.adoc
  modules/ROOT/pages/errors/gql-errors/22NBA.adoc
  modules/ROOT/pages/errors/gql-errors/22NBC.adoc
  modules/ROOT/pages/errors/gql-errors/42NA8.adoc
  modules/ROOT/pages/errors/gql-errors/51N31.adoc
  modules/ROOT/pages/errors/gql-errors/51N41.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cypher-25

#353 Dev merge cypher25
  antora.yml
  modules/ROOT/pages/errors/gql-errors/42N39.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: dev

#345 New Error - Distance metric
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42I62.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: dev, cypher-25, 2025.06

#340 Errors and deprecations for graph references
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42NAA.adoc
  modules/ROOT/pages/errors/gql-errors/51N76.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cypher-25, 2025.06

#356 remove a leftover category (#355)
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked

#358 Removal of old graph reference deprecation.
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 5.x, do not cherry-pick

#359 Added 42I64 - unsupported aggregation
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42I64.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.07

#338 Update 22N69 and 22N71 to have more consistent wording when compared to the corresponding constraint errors
  modules/ROOT/pages/errors/gql-errors/22N69.adoc
  modules/ROOT/pages/errors/gql-errors/22N71.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.07

#361 Update exact neo4j version to 2025.06.2
  antora.yml
Labels: this branch only

#360 42I64 - Unsupported operation
  modules/ROOT/pages/errors/gql-errors/42I64.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.07

#363 Regenerate index file
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.07
