Repository neo4j/docs-status-codes, pull requests merged in 2025-02, with the labels that each got.

#254 Add db name to status description of unrecognized notifications
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: dev, gqlstatus-notifications

#256 bump version to 4.4.41
  antora.yml
Labels: 4.4

#257 bump version to 5.26.2
  antora.yml
Labels: 5.x

#258 Update branches to publish
  package.json
  publish.yml
Labels: dev

#259 bump version to 2025.02
  antora.yml
Labels: 2025.02

#260 Replace 51N27 parameter name item with component
  modules/ROOT/pages/errors/gql-errors/51N27.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2025.02

#261 Change parameters of 22N14
  modules/ROOT/pages/errors/gql-errors/22N14.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: dev, gqlstatus-errors, 2025.02

#262 Change parameters of 22N14
  modules/ROOT/pages/errors/gql-errors.adoc
Labels: cherry picked, 5.x

#263 Update changelog
  modules/ROOT/pages/changelogs.adoc
  modules/ROOT/pages/errors/all-errors.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry-pick this to main

#267 Remove labels `Introduced in 5.x` (#266)
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry picked, main

#271 Update the neo4j-version-exact attribute in the antora.yml file
  antora.yml
Labels: 5.x, this branch only

#270 Document errors implemented in 2025.02
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22N16.adoc
  modules/ROOT/pages/errors/gql-errors/22N59.adoc
  modules/ROOT/pages/errors/gql-errors/22N62.adoc
  modules/ROOT/pages/errors/gql-errors/22N63.adoc
  modules/ROOT/pages/errors/gql-errors/25G02.adoc
  modules/ROOT/pages/errors/gql-errors/42I04.adoc
  modules/ROOT/pages/errors/gql-errors/42I11.adoc
  modules/ROOT/pages/errors/gql-errors/42I12.adoc
  modules/ROOT/pages/errors/gql-errors/42I17.adoc
  modules/ROOT/pages/errors/gql-errors/42I19.adoc
  modules/ROOT/pages/errors/gql-errors/42I33.adoc
  modules/ROOT/pages/errors/gql-errors/42I39.adoc
  modules/ROOT/pages/errors/gql-errors/42I42.adoc
  modules/ROOT/pages/errors/gql-errors/42I46.adoc
  modules/ROOT/pages/errors/gql-errors/42I49.adoc
  modules/ROOT/pages/errors/gql-errors/42I52.adoc
  modules/ROOT/pages/errors/gql-errors/42N26.adoc
  modules/ROOT/pages/errors/gql-errors/42N28.adoc
  modules/ROOT/pages/errors/gql-errors/42N34.adoc
  modules/ROOT/pages/errors/gql-errors/42N35.adoc
  modules/ROOT/pages/errors/gql-errors/42N36.adoc
  modules/ROOT/pages/errors/gql-errors/42N37.adoc
  modules/ROOT/pages/errors/gql-errors/42N38.adoc
  modules/ROOT/pages/errors/gql-errors/42N63.adoc
  modules/ROOT/pages/errors/gql-errors/42N64.adoc
  modules/ROOT/pages/errors/gql-errors/42N69.adoc
  modules/ROOT/pages/errors/gql-errors/50N21.adoc
  modules/ROOT/pages/errors/gql-errors/51N28.adoc
  modules/ROOT/pages/errors/gql-errors/52N24.adoc
  modules/ROOT/pages/errors/gql-errors/G1001.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: 2025.02

#274 Update dev version to 2025.03
  antora.yml
Labels: 2025.03
