Repository neo4j/docs-status-codes, pull requests merged in 2025-06, with the labels that each got.

#337 Update version to 2025.06
  antora.yml
Labels: 2026.06

#291 Remove old Neo4j statuses.
  modules/ROOT/pages/errors/all-errors.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: 2025.06

#335 Fix error message so it makes sense
  modules/ROOT/pages/errors/gql-errors/08N19.adoc
  modules/ROOT/pages/errors/gql-errors/08N20.adoc
  modules/ROOT/pages/errors/gql-errors/08N21.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: 2026.06

#339 Update the exact version to 5.26.8
  antora.yml
Labels: 5.x, this branch only
