Repository neo4j/docs-status-codes, pull requests merged in 2025-05, with the labels that each got.

#300 Change parameter of 42N11 to a list.
  modules/ROOT/pages/errors/gql-errors/42N11.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: 2025.05

#301 Final surface codes
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/42I54.adoc
  modules/ROOT/pages/errors/gql-errors/42I55.adoc
  modules/ROOT/pages/errors/gql-errors/42I56.adoc
  modules/ROOT/pages/errors/gql-errors/42I57.adoc
  modules/ROOT/pages/errors/gql-errors/42I58.adoc
  modules/ROOT/pages/errors/gql-errors/42I59.adoc
  modules/ROOT/pages/errors/gql-errors/42I60.adoc
  modules/ROOT/pages/errors/gql-errors/42I61.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: dev, 2025.05

#307 Update the exact version to 5.26.6
  antora.yml
Labels: 5.x, this branch only

#302 Generate gql-errors index.adoc file
  modules/ROOT/pages/errors/gql-errors/22NA5.adoc
  modules/ROOT/pages/errors/gql-errors/42I33.adoc
  modules/ROOT/pages/errors/gql-errors/42I42.adoc
  modules/ROOT/pages/errors/gql-errors/42I50.adoc
  modules/ROOT/pages/errors/gql-errors/42N18.adoc
  modules/ROOT/pages/errors/gql-errors/42N44.adoc
  modules/ROOT/pages/errors/gql-errors/42N73.adoc
  modules/ROOT/pages/errors/gql-errors/50N10.adoc
  modules/ROOT/pages/errors/gql-errors/50N15.adoc
  modules/ROOT/pages/errors/gql-errors/51N61.adoc
  modules/ROOT/pages/errors/gql-errors/51N62.adoc
  modules/ROOT/pages/errors/gql-errors/53N35.adoc
  modules/ROOT/pages/errors/gql-errors/53N37.adoc
  modules/ROOT/pages/errors/gql-errors/53U00.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/templates/gql-index-template.adoc
  scripts/README.adoc
  scripts/generate-gql-error-index-from-template.py
  scripts/update-gql-error-index.py
  scripts/validate-error-auto-index.py
  scripts/validate-error-index.py
Labels: cherry-pick this to main, cherry-pick-this-to-cypher25

#308 Generate gql-errors index.adoc file (#302)
  modules/ROOT/pages/errors/gql-errors/22NA5.adoc
  modules/ROOT/pages/errors/gql-errors/42I33.adoc
  modules/ROOT/pages/errors/gql-errors/42I42.adoc
  modules/ROOT/pages/errors/gql-errors/42I50.adoc
  modules/ROOT/pages/errors/gql-errors/42N18.adoc
  modules/ROOT/pages/errors/gql-errors/42N44.adoc
  modules/ROOT/pages/errors/gql-errors/42N73.adoc
  modules/ROOT/pages/errors/gql-errors/50N10.adoc
  modules/ROOT/pages/errors/gql-errors/50N15.adoc
  modules/ROOT/pages/errors/gql-errors/51N61.adoc
  modules/ROOT/pages/errors/gql-errors/51N62.adoc
  modules/ROOT/pages/errors/gql-errors/53N35.adoc
  modules/ROOT/pages/errors/gql-errors/53N37.adoc
  modules/ROOT/pages/errors/gql-errors/53U00.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/templates/gql-index-template.adoc
  scripts/README.adoc
  scripts/generate-gql-error-index-from-template.py
  scripts/update-gql-error-index.py
  scripts/validate-error-auto-index.py
  scripts/validate-error-index.py
Labels: cherry picked, main

#310 Update the scripts readme
  scripts/README.adoc
Labels: cherry-pick this to main, cherry-pick-this-to-cypher25

#311 Update the scripts readme (#310)
  scripts/README.adoc
Labels: cherry picked

#312 Update the scripts readme (#310)
  scripts/README.adoc
Labels: cherry picked

#303 Document new GQLSTATUS 22NB9
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22N90.adoc
  modules/ROOT/pages/errors/gql-errors/22NB9.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: 2025.05

#315 Document new GQLSTATUS 22NB9 (#303)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/22N90.adoc
  modules/ROOT/pages/errors/gql-errors/22NB9.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: cherry picked

#314 Fix a heading mistake and the index generation message
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/templates/gql-index-template.adoc
  scripts/generate-gql-error-index-from-template.py
Labels: cherry-pick this to main, cherry-pick-this-to-cypher25

#316 Merge dev into Cypher 25 branch
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/08N19.adoc
  modules/ROOT/pages/errors/gql-errors/08N20.adoc
  modules/ROOT/pages/errors/gql-errors/08N21.adoc
  modules/ROOT/pages/errors/gql-errors/22004.adoc
  modules/ROOT/pages/errors/gql-errors/22012.adoc
  modules/ROOT/pages/errors/gql-errors/22N83.adoc
  modules/ROOT/pages/errors/gql-errors/22NA3.adoc
  modules/ROOT/pages/errors/gql-errors/22NB7.adoc
  modules/ROOT/pages/errors/gql-errors/22NB8.adoc
  modules/ROOT/pages/errors/gql-errors/42I30.adoc
  modules/ROOT/pages/errors/gql-errors/42I54.adoc
  modules/ROOT/pages/errors/gql-errors/42I55.adoc
  modules/ROOT/pages/errors/gql-errors/42I56.adoc
  modules/ROOT/pages/errors/gql-errors/42I57.adoc
  modules/ROOT/pages/errors/gql-errors/42I58.adoc
  modules/ROOT/pages/errors/gql-errors/42I59.adoc
  modules/ROOT/pages/errors/gql-errors/42I60.adoc
  modules/ROOT/pages/errors/gql-errors/42I61.adoc
  modules/ROOT/pages/errors/gql-errors/42N0A.adoc
  modules/ROOT/pages/errors/gql-errors/42N0B.adoc
  modules/ROOT/pages/errors/gql-errors/42N11.adoc
  modules/ROOT/pages/errors/gql-errors/42N25.adoc
  modules/ROOT/pages/errors/gql-errors/42N39.adoc
  modules/ROOT/pages/errors/gql-errors/42N3A.adoc
  modules/ROOT/pages/errors/gql-errors/42N3B.adoc
  modules/ROOT/pages/errors/gql-errors/42N3C.adoc
  modules/ROOT/pages/errors/gql-errors/42N41.adoc
  modules/ROOT/pages/errors/gql-errors/42N52.adoc
  modules/ROOT/pages/errors/gql-errors/42N87.adoc
  modules/ROOT/pages/errors/gql-errors/42N92.adoc
  modules/ROOT/pages/errors/gql-errors/42N94.adoc
  modules/ROOT/pages/errors/gql-errors/42N95.adoc
  modules/ROOT/pages/errors/gql-errors/42N96.adoc
  modules/ROOT/pages/errors/gql-errors/42NA0.adoc
  modules/ROOT/pages/errors/gql-errors/42NA1.adoc
  modules/ROOT/pages/errors/gql-errors/42NA2.adoc
  modules/ROOT/pages/errors/gql-errors/42NA3.adoc
  modules/ROOT/pages/errors/gql-errors/42NA4.adoc
  modules/ROOT/pages/errors/gql-errors/50N18.adoc
  modules/ROOT/pages/errors/gql-errors/50N19.adoc
  modules/ROOT/pages/errors/gql-errors/50N20.adoc
  modules/ROOT/pages/errors/gql-errors/51N31.adoc
  modules/ROOT/pages/errors/gql-errors/51N58.adoc
  modules/ROOT/pages/errors/gql-errors/52N21.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
  modules/ROOT/templates/gql-index-template.adoc
  scripts/generate-gql-error-index-from-template.py
Labels: cypher-25

#320 Update the version number to 4.4.43
  antora.yml
Labels: 4.4, this branch only

#317 Add some missing glossary entries and fix 42I14
  modules/ROOT/pages/errors/gql-errors/42I14.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: cherry-pick this to main, cherry-pick-this-to-cypher25

#323 Add some missing glossary entries and fix 42I14 (#317)
  modules/ROOT/pages/errors/gql-errors/42I14.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/partials/glossary.adoc
Labels: cherry picked

#322 Add some missing glossary entries and fix 42I14 (#317)
  modules/ROOT/pages/errors/gql-errors/42I14.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
  modules/ROOT/pages/notifications/all-notifications.adoc
  modules/ROOT/partials/glossary.adoc
Labels: cherry picked, main

#318 Update the readme file
  README.adoc
Labels: cherry-pick this to main, cherry-pick-this-to-cypher25

#324 Update the readme file (#318)
  README.adoc
Labels: cherry picked

#313 Add a note that error messages are deprecated
  modules/ROOT/pages/errors/all-errors.adoc
Labels: cherry-pick this to main, cherry-pick-this-to-cypher25

#331 Update to 4.4.44
  antora.yml
Labels: 4.4, this branch only

#330 "or an application-generated id" -> "or consider using an application-generated id"
  modules/ROOT/pages/notifications/all-notifications.adoc
Labels: cherry-pick-this-to-cypher25

#321 Add 52N40 and 52N41
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/52N40.adoc
  modules/ROOT/pages/errors/gql-errors/52N41.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: cherry-pick-this-to-cypher25, 2025.05

#333 Add 52N40 and 52N41 (#321)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/errors/gql-errors/52N40.adoc
  modules/ROOT/pages/errors/gql-errors/52N41.adoc
  modules/ROOT/pages/errors/gql-errors/index.adoc
Labels: cherry picked
